name: Publish to PyPI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          python3 -m pip install poetry
      - name: Build
        run: |
          poetry build
      - name: Store distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Cleanup
        if: always()
        run: |
          rm -rf *.egg-info dist

  publish-to-pypi:
    if: startsWith(github.ref, 'refs/tags/v') # Only run publish on version tags
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi-publish
      url: https://pypi.org/p/aerie-cli
    permissions:
      id-token: write
  
    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: test-pypi-publish
      url: https://test.pypi.org/p/aerie-cli

    permissions:
      id-token: write

    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
